[project]
name = "current-ai"
version = "0.1.0"
description = "AI test backend"
requires-python = "==3.13.2"

dependencies = [
  "fastapi",
  "uvicorn[standard]",
  "openai",
  "anthropic",
  "rich"
]

[dependency-groups]
dev = [
    "black>=25.12.0",
    "ruff>=0.14.10",
]

[tool.black]
line-length = 88
target-version = ["py311"]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "F", "I"]